### ISSUE TITLE
Cache shop specific rules

### ISSUE THREAD

**Issue by deeps96** [HPI-BP2017N2/ShopRulesGenerator-deprecated-#7]
**AS** a ShopRulesGenerator
**I WANT TO** use a cache solution
**TO** reduce the amount of work required producing shop rules.

**ACCEPTANCE CRITERIA**
- [ ] If a rule was created within a specified time ago, this rule should get returned directly using the route defined in #6.
- [ ] If the rule is older then the specified time, its expected to regenerate the rule as described in #6

**Comment by deeps96** [comment]
** Tasks for creating a new shop-specific rule **

- [ ] Fetch 10 offers using the BPBridge route getRandomOffers
- [ ] Use the URLCleaner to bulk(!) clean the product-url of each offer
- [ ] For each offer download the cleaned url, search the product attributes and generate a minimal selector path.
- [ ] Merge all gathered selectors per product attribute to ensure a 100% match if possible.
- [ ] Build a JSON and map to each product attribute the resulting selector.
